apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: decoding-sdk-server
  name: decoding-sdk-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: decoding-sdk-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../decoding-sdk/docker-compose.yml --
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: decoding-sdk-server
    spec:
      containers:
        - args:
            - /home/speechuser/start_master.sh
            - -p
            - "8010"
          image: lyvt/decoding-sdk:1.0
          name: decoding-sdk-server
          ports:
            - containerPort: 8010
          resources: {}
      restartPolicy: Always
status: {}
